name: dash
channels:
  - conda-forge
dependencies:
  - wradlib
  - scikit-learn
  - pillow
  - h5py
  - pandas
  - xarray
  - requests
  - netcdf4
  - arm_pyart>=1.11.8
  - dask
  - matplotlib
  - seaborn
  - numpy
  - pyproj
  - scipy
  - ipython
  - ca-certificates
  - certifi
  - openssl
  - tqdm
  - scikit-image
  - dash
  - plotly
  - flask
  - flask-compress
  - ipdb
  - arrow
  - dash-bootstrap-components
  - dash-core-components
  - dash-mantine-components==0.12.1
